config/routes.rb
CacheManager::Engine.routes.draw do

  resources :stats, only: :index
  resources :keys, only: [:index, :show] do
    put :flush, on: :collection
  end

  root to: "stats#index"
end

app/models/cache_manager/key.rb
module CacheManager
  class Key
    EXCLUDED_DIRS = ['.', '..', 'assets'].freeze

    attr_reader :klass

    def initialize
      @klass = Rails.cache.class.to_s
    end

    # Rails.cache.instance_variable_get(:@data).keys
    class << self
      def all
        new.all
      end

      def flush(id)
        if id == 'all'
          Rails.cache.clear
        else
          Rails.cache.delete(id)
       end
      end

      def find(id)
        Rails.cache.read(id)
      end

      def destroy(id)
        Rails.cache.delete(id)
      end
    end

    def all
      case @klass
      when 'ActiveSupport::Cache::FileStore'
        keys_for_file_store
      else
        keys_for_memory_store
      end
    end

    def keys_for_memory_store
      Rails.cache.instance_variable_get(:@data).keys
    end

    def keys_for_file_store
      cache_path = Rails.cache.instance_variable_get(:'@cache_path')
      root_dirs = Dir.entries(cache_path).reject { |f| (EXCLUDED_DIRS + ['.gitkeep']).include?(f) }
      full_paths = root_dirs.collect { |i| cache_path + "#{i}" }
      full_paths.collect do |dir|
        File.basename(Dir["#{dir}/*/*"][0]) if Dir["#{dir}/*/*"][0]
      end
    end
  end
end

app/models/cache_manager/stats.rb
module CacheManager
  class Stats
    attr_reader :klass

    def initialize
      @klass = Rails.cache.class.to_s
    end

    class << self
      def all
        new.all
      end
    end

    def all
      case @klass
      when 'ActiveSupport::Cache::FileStore'
        {}
      else
        Rails.cache.stats
      end
    end
  end
end

app/models/cache_reader/key.rb
module CacheReader
  class Key

    #Rails.cache.instance_variable_get(:@data).keys
    class << self
      def all
        Rails.cache.instance_variable_get(:@data).keys
      end

      def find(id)
        Rails.cache.read(id)
      end
    end
  end
end

app/models/cache_reader/stats.rb
module CacheReader
  class Stats

    #Rails.cache.instance_variable_get(:@data).keys
    class << self
      def all
        Rails.cache.stats
      end
    end
  end
end

app/controllers/cache_manager/application_controller.rb
module CacheManager
  class ApplicationController < ActionController::Base
  end
end

app/controllers/cache_manager/keys_controller.rb
require_dependency "cache_manager/application_controller"

module CacheManager
  class KeysController < ApplicationController
    def index
      @keys = Key.all
    end

    def show
      @key = Key.find(params[:id])
    end

    def flush
      @key = Key.flush(params[:key])
      respond_to do |format|
        format.html { redirect_to keys_url, notice: 'Keys were successfully flushed.' }
      end
    end
  end
end

app/controllers/cache_manager/stats_controller.rb
require_dependency "cache_manager/application_controller"

module CacheManager
  class StatsController < ApplicationController
    def index
      @stats = Stats.all
    end
  end
end

app/controllers/cache_reader/keys_controller.rb
require_dependency "cache_reader/application_controller"

module CacheReader
  class KeysController < ApplicationController
    def index
      @keys = Key.all
    end

    def show
      @key = Key.find(params[:id])
    end
  end
end

app/controllers/cache_reader/stats_controller.rb
require_dependency "cache_reader/application_controller"

module CacheReader
  class StatsController < ApplicationController
    def index
      @stats = Stats.all
    end
  end
end

app/helpers/cache_manager/application_helper.rb
module CacheManager
  module ApplicationHelper
  end
end

app/helpers/cache_reader/application_helper.rb
module CacheReader
  module ApplicationHelper
  end
end

app/views/cache_manager/keys/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>
      <%= pluralize(@keys.count, 'key') %>
    </h1>
  </div>
  <div class="col-md-4">
    <%= form_tag({controller: :keys, action: :flush}, method: "put") do %>
    <%= hidden_field_tag :key, 'all' %>
    <%= submit_tag "Flush All Keys" ,class: 'btn btn-block btn-danger' %>
    <% end %>
  </div>
</div>

<table class="table">
  <thead>
    <th>
      Key
    </th>
    <th>
      Action
    </th>
  </thead>
  <tbody>
    <% @keys.each do |key| %>
    <tr>
      <td>
        <%= link_to key, key_url(id: key) %>
      </td>
      <td>
        <%#= link_to 'Delete', '#',class: 'btn btn-danger btn-xs' %>
        <%= form_tag({controller: :keys, action: :flush}, method: "put") do %>
        <%= hidden_field_tag :key, key %>
        <%= submit_tag "Flush" ,class: 'btn btn-danger btn-xs' %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/cache_manager/keys/show.html.erb
<%= debug @key %>

app/views/cache_manager/stats/index.html.erb
<div class="jumbotron">
  <h2>Environment: <%= Rails.env.humanize %></h2>
  <h2>Cache Store: <%= Rails.cache.class %></h2>
</div>


<% if @stats.present? %>
<table class="table">
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    <% @stats.each_pair do |key, value| %>
    <tr>
      <td>
        <%= key.humanize %>
      </td>
      <td>
        <%= value %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/layouts/cache_manager/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cache Manager</title>
    <%= stylesheet_link_tag    "cache_manager/application", media: "all" %>
    <%= javascript_include_tag "cache_manager/application" %>
    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/paper/bootstrap.min.css" rel="stylesheet"> -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/cosmo/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>
  <body>
  <%= render partial: 'shared/navbar' %>
    <div class="container">
      <div class="row">
        <% if notice.present? %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/cache_reader/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CacheReader</title>
    <%= stylesheet_link_tag    "cache_reader/application", media: "all" %>
    <%= javascript_include_tag "cache_reader/application" %>
    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/paper/bootstrap.min.css" rel="stylesheet"> -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/cosmo/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>
  <body>
  <%= render partial: 'shared/navbar' %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, class: "navbar-brand" do  %>
        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> 
        Cache Manager
        <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
      <% end -%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to 'Stats', stats_url %></li>
        <li> <%= link_to 'Keys', keys_url %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>